const constants = {
	ADD_DAY: "ADD_DAY",
	REMOVE_DAY: "REMOVE_DAY",
	SET_GOAL: "SET_GOAL",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
	CANCEL_FETCHING: "CANCEL_FETCHING",
	CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
	FETCH_SKI_DAYS: "FETCH_SKI_DAYS", 
	CANCEL_FETCHING_SKI_DAYS: "CANCEL_FETCHING_SKI_DAYS", 
	FETCH_SKI_DAYS_COMPLETED: "FETCH_SKI_DAYS_COMPLETED", 
}

export default constants